// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmep9VJUZaGAnUTHElN-W1cs0jx2sHc-8',
    appId: '1:998971120352:web:e63a93e474eb23d2c6ce85',
    messagingSenderId: '998971120352',
    projectId: 'delishop-5bd8e',
    authDomain: 'delishop-5bd8e.firebaseapp.com',
    storageBucket: 'delishop-5bd8e.firebasestorage.app',
    measurementId: 'G-51TR1F8EQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSTmRzga952F9I7H2CykBex-zQB9YWvRk',
    appId: '1:998971120352:android:3eb314bd87d58168c6ce85',
    messagingSenderId: '998971120352',
    projectId: 'delishop-5bd8e',
    storageBucket: 'delishop-5bd8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMSrkzC0TtWGgh6fx_qyft4Ts8co99SGo',
    appId: '1:998971120352:ios:a7d02efc637febc0c6ce85',
    messagingSenderId: '998971120352',
    projectId: 'delishop-5bd8e',
    storageBucket: 'delishop-5bd8e.firebasestorage.app',
    iosBundleId: 'com.example.delishop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMSrkzC0TtWGgh6fx_qyft4Ts8co99SGo',
    appId: '1:998971120352:ios:a7d02efc637febc0c6ce85',
    messagingSenderId: '998971120352',
    projectId: 'delishop-5bd8e',
    storageBucket: 'delishop-5bd8e.firebasestorage.app',
    iosBundleId: 'com.example.delishop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmep9VJUZaGAnUTHElN-W1cs0jx2sHc-8',
    appId: '1:998971120352:web:757685dab8e53a37c6ce85',
    messagingSenderId: '998971120352',
    projectId: 'delishop-5bd8e',
    authDomain: 'delishop-5bd8e.firebaseapp.com',
    storageBucket: 'delishop-5bd8e.firebasestorage.app',
    measurementId: 'G-83D1FC339Z',
  );
}
